### PR TITLE
Travis CI integration and AppImage generation

### PR DESCRIPTION
**Pull request by aferrero2707**
This pull request adds a Travis CI configuration file for running automatic Linux building, plus the automatic generation of an AppImage package that is stored on transfer.sh

The application is built against the GIT version of LibRAW.

The building and updating of the AppImage package is trigger by any commit into the master branch.

Other, more convenient storage solutions for the AppImage might be possible, however transfer.sh was the easiest option for the initial testing.

### CODE REVIEW

**Comment by heckflosse** [comment]
@aferrero2707 Thank you very much :+1:

**Comment by probonopd** [comment]
Great work @aferrero2707 and @heckflosse. Maybe you are interested in https://github.com/probonopd/uploadtool, a super simple tool to upload continuous builds (each push) to a "continuous" release on [GitHub Releases](https://github.com/jcelaya/hdrmerge/releases).

**Comment by Beep6581** [comment]
> package that is stored on transfer.sh

@aferrero2707 could you explain what that means? I don't see that file anywhere.

**Comment by aferrero2707** [comment]
> I don't see that file anywhere.

The complete URL of the file on transfer.sh is only visible in the Travis CI log.

Anyhow, the solution that @probonopd proposes is muuuuuuch better and still almost as simple, so I strongly suggest to go for that. I am going to test it on PhotoFlow as soon as I manage...

**Comment by Beep6581** [comment]
@jcelaya hey, I tried enabling the HDRMerge repo on Travis-CI but I can only do that for my own repos, so only for my own fork `beep6581/hdrmerge` not for `jcelaya/hdrmerge`. You seem to be the only one who can log into https://travis-ci.org/profile/ and enable it for this repo.

**Comment by Beep6581** [comment]
@aferrero2707 could you explain where one finds these appimages in https://github.com/jcelaya/hdrmerge/issues/95 ? No rush, I'm loaded with work at the moment anyway.

**Pull request merged**
