### PR TITLE
Fix Qt 5.15 deprecation warnings

### PR DESCRIPTION
**Pull request by Floessie**
Compile-tested on Debian AMD64

- Testing: Qt 5.15
- Buster: Qt 5.11
- Stretch: Qt 5.7

### CODE REVIEW

**Comment by heckflosse** [comment]
@Floessie I have no time to test this on windows. But I can press the merge button. Shall I?

**Comment by Floessie** [comment]
Hm, maybe @Thanatomanic has the time for a quick test on Windows. Otherwise just hit the button and forward the complains. :wink:

**Comment by heckflosse** [comment]
I'll wait for @Thanatomanic

**Comment by Thanatomanic** [comment]
If this is somewhat urgent, please don't rely on me as my time is currently very limited.

**Comment by heckflosse** [comment]
@Thanatomanic I don't think it's urgent. Let @Floessie decide when to merge it ;-)

**Comment by Floessie** [comment]
@heckflosse IMHO, just merge. The only problem that could possibly arise is the `angleDelta()` change, which I've already incorporated into one of my projects.

**Pull request merged**
